theme: jekyll-theme-minimal
title: williamgrim.com
description: |
  Greater St. Louis Area<br>
  <br>
  Data science, DevOps, and Software Engineering<br>
  <br>
  My motivation is to develop knowledge and products that enhance the world
  and make life easier.
